### ISSUE TITLE
wrong link?

### ISSUE THREAD

**Issue by spamegg1** [FullStack-HY/part3-notes-backend#1]
Not sure if this is the right place for this.
Here: https://fullstackopen.com/en/part4/testing_the_backend#refactoring-tests
At the end of the section there is a link: 
https://github.com/fullstack-hy/part3-notes-backend/tree/part4-6
which returns "Page not found".
The branches go from part4-5 to part4-8.
There is this:
https://github.com/fullstack-hy2020/part3-notes-backend/tree/part4-6
but this is 15 months old?

**Comment by spamegg1** [comment]
Same issue with the link at the end of this section here:
https://fullstackopen.com/en/part4/user_administration#creating-users
This link returns "Page not found":
https://github.com/fullstack-hy/part3-notes-backend/tree/part4-7
Again there is this, but 15 months old:
https://github.com/fullstack-hy2020/part3-notes-backend/tree/part4-7

**Comment by RayRemnant** [comment]
Yeah just stumbled across the same problem, the two branches (**part4-6** and **part4-7**) are missing.
Couldn't find any contacting info to notify the problem, hopefully this is enough.

**Comment by spamegg1** [comment]
@RayRemnant I believe the author does not check these repos, but he checks pull requests to the main repo: 
https://github.com/fullstack-hy2020/fullstack-hy2020.github.io/pulls
I can't make a PR because I don't have replacement links for these.
